# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import BizServer_pb2 as BizServer__pb2


class GetUsersServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUsers = channel.unary_unary(
                '/BizServer.GetUsersService/GetUsers',
                request_serializer=BizServer__pb2.GetUsersRequest.SerializeToString,
                response_deserializer=BizServer__pb2.GetUsersResponse.FromString,
                )
        self.GetUsersWithInjection = channel.unary_unary(
                '/BizServer.GetUsersService/GetUsersWithInjection',
                request_serializer=BizServer__pb2.GetUsersWithInjectionRequest.SerializeToString,
                response_deserializer=BizServer__pb2.GetUsersResponse.FromString,
                )


class GetUsersServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUsersWithInjection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetUsersServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsers,
                    request_deserializer=BizServer__pb2.GetUsersRequest.FromString,
                    response_serializer=BizServer__pb2.GetUsersResponse.SerializeToString,
            ),
            'GetUsersWithInjection': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUsersWithInjection,
                    request_deserializer=BizServer__pb2.GetUsersWithInjectionRequest.FromString,
                    response_serializer=BizServer__pb2.GetUsersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'BizServer.GetUsersService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetUsersService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BizServer.GetUsersService/GetUsers',
            BizServer__pb2.GetUsersRequest.SerializeToString,
            BizServer__pb2.GetUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUsersWithInjection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/BizServer.GetUsersService/GetUsersWithInjection',
            BizServer__pb2.GetUsersWithInjectionRequest.SerializeToString,
            BizServer__pb2.GetUsersResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
