# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AuthService.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x41uthService.proto\x12\x05proto\"3\n\x0ereq_pq_Request\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x12\n\nmessage_id\x18\x02 \x01(\x05\"`\n\x0freq_pq_Response\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\t\n\x01p\x18\x04 \x01(\x05\x12\t\n\x01g\x18\x05 \x01(\x05\"T\n\x0ereq_dh_Request\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\t\n\x01\x41\x18\x04 \x01(\x05\"U\n\x0freq_dh_Response\x12\r\n\x05nonce\x18\x01 \x01(\t\x12\x14\n\x0cserver_nonce\x18\x02 \x01(\t\x12\x12\n\nmessage_id\x18\x03 \x01(\x05\x12\t\n\x01\x42\x18\x04 \x01(\x05\"\x18\n\x04Seek\x12\x10\n\x08\x61uth_key\x18\x01 \x01(\x05\"\x18\n\x07\x43onfirm\x12\r\n\x05valid\x18\x01 \x01(\x08\x32\xba\x01\n\x0c\x41uth_Service\x12\x39\n\x06req_pq\x12\x15.proto.req_pq_Request\x1a\x16.proto.req_pq_Response\"\x00\x12@\n\rreq_DH_params\x12\x15.proto.req_dh_Request\x1a\x16.proto.req_dh_Response\"\x00\x12-\n\x0c\x41uthenticate\x12\x0b.proto.Seek\x1a\x0e.proto.Confirm\"\x00\x42\x0fZ\rweb_hw1/protob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'AuthService_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\rweb_hw1/proto'
  _REQ_PQ_REQUEST._serialized_start=28
  _REQ_PQ_REQUEST._serialized_end=79
  _REQ_PQ_RESPONSE._serialized_start=81
  _REQ_PQ_RESPONSE._serialized_end=177
  _REQ_DH_REQUEST._serialized_start=179
  _REQ_DH_REQUEST._serialized_end=263
  _REQ_DH_RESPONSE._serialized_start=265
  _REQ_DH_RESPONSE._serialized_end=350
  _SEEK._serialized_start=352
  _SEEK._serialized_end=376
  _CONFIRM._serialized_start=378
  _CONFIRM._serialized_end=402
  _AUTH_SERVICE._serialized_start=405
  _AUTH_SERVICE._serialized_end=591
# @@protoc_insertion_point(module_scope)
