# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import AuthService_pb2 as AuthService__pb2


class Auth_ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.req_pq = channel.unary_unary(
                '/proto.Auth_Service/req_pq',
                request_serializer=AuthService__pb2.req_pq_Request.SerializeToString,
                response_deserializer=AuthService__pb2.req_pq_Response.FromString,
                )
        self.req_DH_params = channel.unary_unary(
                '/proto.Auth_Service/req_DH_params',
                request_serializer=AuthService__pb2.req_dh_Request.SerializeToString,
                response_deserializer=AuthService__pb2.req_dh_Response.FromString,
                )
        self.Authenticate = channel.unary_unary(
                '/proto.Auth_Service/Authenticate',
                request_serializer=AuthService__pb2.Seek.SerializeToString,
                response_deserializer=AuthService__pb2.Confirm.FromString,
                )


class Auth_ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def req_pq(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def req_DH_params(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Auth_ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'req_pq': grpc.unary_unary_rpc_method_handler(
                    servicer.req_pq,
                    request_deserializer=AuthService__pb2.req_pq_Request.FromString,
                    response_serializer=AuthService__pb2.req_pq_Response.SerializeToString,
            ),
            'req_DH_params': grpc.unary_unary_rpc_method_handler(
                    servicer.req_DH_params,
                    request_deserializer=AuthService__pb2.req_dh_Request.FromString,
                    response_serializer=AuthService__pb2.req_dh_Response.SerializeToString,
            ),
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=AuthService__pb2.Seek.FromString,
                    response_serializer=AuthService__pb2.Confirm.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.Auth_Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Auth_Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def req_pq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Auth_Service/req_pq',
            AuthService__pb2.req_pq_Request.SerializeToString,
            AuthService__pb2.req_pq_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def req_DH_params(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Auth_Service/req_DH_params',
            AuthService__pb2.req_dh_Request.SerializeToString,
            AuthService__pb2.req_dh_Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.Auth_Service/Authenticate',
            AuthService__pb2.Seek.SerializeToString,
            AuthService__pb2.Confirm.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
